name: my_first_ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci_jobs:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run index file
        run: node index.js
